export interface StepData {
  number: string;
  id: string;
  chapter: number;
  chapterName: string;
  name: string;
  subtitle: string;
  description: string;
  detailedText: string;
  verseRef: string;
  verseText: string;
  colorAccent: string;
  badgeBg: string;
  iconType: string;
  primaryCtaText: string;
  primaryCtaAction: 'JESUS' | 'VISIT' | 'CHAT';
  secondaryCtaText?: string;
  whatsappMessage: string;
}

export const NINE_STEPS: StepData[] = [
  {
    number: '01',
    id: 'paso-01-aceptar-a-jesus',
    chapter: 1,
    chapterName: 'Capítulo I: Comenzar',
    name: 'Aceptar a Jesús',
    subtitle: 'Todo comienza con una decisión de fe',
    description: 'Aceptar a Jesús es reconocerlo como Señor y Salvador, recibir el perdón de Dios y comenzar una nueva vida con Él. No necesitas tener todo resuelto para acercarte a Dios. Puedes comenzar hoy.',
    detailedText: 'Al dar este paso, entras en una relación viva con Dios. Tu pasado queda perdonado, recibes identidad de hijo de Dios y el Espíritu Santo comienza a guiar tus pasos día con día.',
    verseRef: 'Romanos 10:9',
    verseText: 'Que si confesares con tu boca que Jesús es el Señor, y creyeres en tu corazón que Dios le levantó de los muertos, serás salvo.',
    colorAccent: '#00E5FF',
    badgeBg: 'bg-cyan-electric/20 text-cyan-electric border-cyan-electric/40',
    iconType: 'Sparkles',
    primaryCtaText: 'Quiero hacer la oración de fe',
    primaryCtaAction: 'JESUS',
    secondaryCtaText: 'Platicar con un pastor',
    whatsappMessage: 'Hola, he completado el Paso 01 (Aceptar a Jesús) en la web y me gustaría recibir orientación espiritual.',
  },
  {
    number: '02',
    id: 'paso-02-encuentro',
    chapter: 1,
    chapterName: 'Capítulo I: Comenzar',
    name: 'Encuentro',
    subtitle: 'Sanidad del corazón y libertad interior',
    description: 'Un retiro de fin de semana enfocado en experimentar el amor paternal de Dios, sanar heridas del pasado, romper ataduras y recibir un nuevo aliento espiritual.',
    detailedText: 'En el Encuentro te desconectas del ruido diario para escuchar la voz de Dios. Es un espacio seguro donde el perdón restaura familias y el corazón encuentra descanso genuino.',
    verseRef: 'Salmo 147:3',
    verseText: 'Él sana a los quebrantados de corazón, y venda sus heridas.',
    colorAccent: '#FFB74D',
    badgeBg: 'bg-amber-500/20 text-amber-300 border-amber-500/40',
    iconType: 'Heart',
    primaryCtaText: 'Saber más sobre el Encuentro',
    primaryCtaAction: 'CHAT',
    whatsappMessage: 'Hola, me gustaría recibir información sobre la próxima fecha del retiro de Encuentro.',
  },
  {
    number: '03',
    id: 'paso-03-bautismo-en-agua',
    chapter: 1,
    chapterName: 'Capítulo I: Comenzar',
    name: 'Bautismo en Agua',
    subtitle: 'Testimonio público de tu nueva vida',
    description: 'El paso visible de fe donde sepultas la vieja naturaleza y te levantas simbólica y espiritualmente a una vida resucitada en Cristo Jesús.',
    detailedText: 'El bautismo no es un requisito para que Dios te ame, sino una hermosa fiesta de obediencia y testimonio ante la iglesia y el mundo de que has decidido seguir a Jesús para siempre.',
    verseRef: 'Romanos 6:4',
    verseText: 'Porque somos sepultados juntamente con él para muerte por el bautismo, a fin de que como Cristo resucitó de los muertos por la gloria del Padre, así también nosotros andemos en vida nueva.',
    colorAccent: '#00B4D8',
    badgeBg: 'bg-sky-500/20 text-sky-300 border-sky-500/40',
    iconType: 'Waves',
    primaryCtaText: 'Quiero bautizarme',
    primaryCtaAction: 'CHAT',
    whatsappMessage: 'Hola, tengo interés en bautizarme en agua en Amistad Nueva Creación.',
  },
  {
    number: '04',
    id: 'paso-04-congregarse',
    chapter: 2,
    chapterName: 'Capítulo II: Crecer',
    name: 'Congregarse',
    subtitle: 'Caminar juntos como familia espiritual',
    description: 'La vida cristiana fue diseñada para vivirse en comunidad. Congregarte cada semana te fortalece, te brinda cobertura y te rodea de personas que oran por ti.',
    detailedText: 'Al asistir a nuestras reuniones dominicales y tiempos de oración, tu fe se nutre de la Palabra predicada y de la alabanza colectiva. La iglesia es tu hogar espiritual.',
    verseRef: 'Hebreos 10:24-25',
    verseText: 'Y considerémonos unos a otros para estimularnos al amor y a las buenas obras; no dejando de congregarnos, como algunos tienen por costumbre...',
    colorAccent: '#48CAE4',
    badgeBg: 'bg-teal-500/20 text-teal-300 border-teal-500/40',
    iconType: 'Users',
    primaryCtaText: 'Ver horarios de reuniones',
    primaryCtaAction: 'VISIT',
    whatsappMessage: 'Hola, quisiera planear mi asistencia a una de sus reuniones dominicales.',
  },
  {
    number: '05',
    id: 'paso-05-mayordomia',
    chapter: 2,
    chapterName: 'Capítulo II: Crecer',
    name: 'Mayordomía',
    subtitle: 'Honrar a Dios con todo lo que somos',
    description: 'Reconocer que nuestra vida, talentos, tiempo y recursos provienen de la gracia de Dios, aprendiendo a administrarlos con sabiduría, propósito y generosidad.',
    detailedText: 'La mayordomía bíblica transforma nuestra perspectiva: dejamos de vivir con afán para vivir con mayordomía fiel, bendiciendo a otros y sembrando en el Reino eterno.',
    verseRef: '2 Corintios 9:7',
    verseText: 'Cada uno dé como propuso en su corazón: no con tristeza, ni por necesidad, porque Dios ama al dador alegre.',
    colorAccent: '#E0A96D',
    badgeBg: 'bg-amber-600/20 text-amber-200 border-amber-500/40',
    iconType: 'Gift',
    primaryCtaText: 'Aprender sobre mayordomía',
    primaryCtaAction: 'CHAT',
    whatsappMessage: 'Hola, me gustaría aprender más sobre los principios bíblicos de mayordomía.',
  },
  {
    number: '06',
    id: 'paso-06-discipulado',
    chapter: 2,
    chapterName: 'Capítulo II: Crecer',
    name: 'Discipulado',
    subtitle: 'Raíces profundas en la Palabra de Dios',
    description: 'Aprender a caminar día a día conforme al modelo de Cristo mediante el estudio sistemático de las Escrituras y el acompañamiento pastoral.',
    detailedText: 'A través de nuestras clases de discipulado aprenderás doctrina bíblica fundamental, cómo orar con eficacia, defender tu fe y formar un carácter maduro e inquebrantable.',
    verseRef: 'Mateo 28:19-20',
    verseText: 'Por tanto, id, y haced discípulos a todas las naciones... enseñándoles que guarden todas las cosas que os he mandado; y he aquí yo estoy con vosotros todos los días...',
    colorAccent: '#90E0EF',
    badgeBg: 'bg-cyan-600/20 text-cyan-200 border-cyan-500/40',
    iconType: 'BookOpen',
    primaryCtaText: 'Inscribirme a discipulado',
    primaryCtaAction: 'CHAT',
    whatsappMessage: 'Hola, me interesa inscribirme en el curso de discipulado de la iglesia.',
  },
  {
    number: '07',
    id: 'paso-07-servir-a-jesus',
    chapter: 3,
    chapterName: 'Capítulo III: Vivir y Servir',
    name: 'Servir a Jesús',
    subtitle: 'Tus dones y talentos puestos en acción',
    description: 'Descubrir el propósito para el cual fuiste creado, integrándote a un ministerio donde tus habilidades sirvan para bendecir a otros y edificar la iglesia.',
    detailedText: 'Ya sea en alabanza, bienvenida, enseñanza a niños, multimedia, intercesión o logística, hay un lugar especialmente preparado para que sirvas con alegría.',
    verseRef: '1 Pedro 4:10',
    verseText: 'Cada uno según el don que ha recibido, minístrelo a los otros, como buenos administradores de la multiforme gracia de Dios.',
    colorAccent: '#00F5D4',
    badgeBg: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40',
    iconType: 'Flame',
    primaryCtaText: 'Quiero servir en un ministerio',
    primaryCtaAction: 'CHAT',
    whatsappMessage: 'Hola, me gustaría integrarme como voluntario en un equipo de servicio.',
  },
  {
    number: '08',
    id: 'paso-08-grupo-de-amistad',
    chapter: 3,
    chapterName: 'Capítulo III: Vivir y Servir',
    name: 'Grupo de Amistad',
    subtitle: 'Comunidad viva y cercana en los hogares',
    description: 'Reuniones en casas por distintos sectores de Querétaro para convivir en confianza, estudiar la Biblia, compartir una comida y cuidarnos mutuamente.',
    detailedText: 'En los Grupos de Amistad nadie camina solo. Es el espacio íntimo donde nacen amistades entrañables, se ora por necesidades familiares y se experimenta la iglesia en tu vecindario.',
    verseRef: 'Hechos 2:46-47',
    verseText: 'Y perseverando unánimes cada día en el templo, y partiendo el pan en las casas, comían juntos con alegría y sencillez de corazón...',
    colorAccent: '#FFD166',
    badgeBg: 'bg-yellow-500/20 text-yellow-200 border-yellow-500/40',
    iconType: 'Home',
    primaryCtaText: 'Encontrar mi Grupo de Amistad',
    primaryCtaAction: 'CHAT',
    whatsappMessage: 'Hola, quisiera conocer qué Grupo de Amistad se reúne cerca de mi zona en Querétaro.',
  },
  {
    number: '09',
    id: 'paso-09-reencuentro',
    chapter: 3,
    chapterName: 'Capítulo III: Vivir y Servir',
    name: 'Reencuentro',
    subtitle: 'Profundizar, fortalecer y continuar',
    description: 'El Reencuentro es una segunda etapa después del Encuentro. Es un tiempo para volver a buscar a Dios de manera intencional, profundizar en lo aprendido, fortalecer áreas de la vida espiritual y continuar el proceso de crecimiento y restauración.',
    detailedText: 'En esta segunda etapa, el énfasis está en fortalecer áreas de la vida espiritual y dar continuidad al proceso de crecimiento y restauración iniciado en el Encuentro.',
    verseRef: 'Filipenses 1:6',
    verseText: 'Estando persuadido de esto, que el que comenzó en vosotros la buena obra, la perfeccionará hasta el día de Jesucristo.',
    colorAccent: '#00E5FF',
    badgeBg: 'bg-cyan-electric/20 text-cyan-electric border-cyan-electric/40',
    iconType: 'Compass',
    primaryCtaText: 'Conocer sobre el Reencuentro',
    primaryCtaAction: 'CHAT',
    whatsappMessage: 'Hola, me gustaría saber cuándo será el próximo retiro de Reencuentro.',
  },
];
